//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Commons.Reporting.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Commons.Reporting.Strings.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all paths return in function &apos;{0}&apos;..
        /// </summary>
        internal static string AllPathsMustReturn {
            get {
                return ResourceManager.GetString("AllPathsMustReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; requires void return parameter..
        /// </summary>
        internal static string AttributeRequiresVoidReturnType {
            get {
                return ResourceManager.GetString("AttributeRequiresVoidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; requires zero function parameters..
        /// </summary>
        internal static string AttributeRequiresZeroParameters {
            get {
                return ResourceManager.GetString("AttributeRequiresZeroParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad character input &apos;{0}&apos;..
        /// </summary>
        internal static string BadCharacterInput {
            get {
                return ResourceManager.GetString("BadCharacterInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator &apos;{0}&apos; is not defined for types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string BinaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("BinaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function symbol &apos;{0}&apos; already declared..
        /// </summary>
        internal static string BinderFunctionAlreadyExists {
            get {
                return ResourceManager.GetString("BinderFunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle {0}&apos; already declared..
        /// </summary>
        internal static string BundleAlreadyExists {
            get {
                return ResourceManager.GetString("BundleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string BundleDoesNotExist {
            get {
                return ResourceManager.GetString("BundleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; could not be declared..
        /// </summary>
        internal static string CannotBindParameter {
            get {
                return ResourceManager.GetString("CannotBindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type of &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CannotConvertType {
            get {
                return ResourceManager.GetString("CannotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type of &apos;{0}&apos; to &apos;{1}&apos;. An explicit conversion exists (are you missing a cast?)..
        /// </summary>
        internal static string CannotConvertTypeImplicity {
            get {
                return ResourceManager.GetString("CannotConvertTypeImplicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reassign value of read-only variable &apos;{0}&apos;..
        /// </summary>
        internal static string CannotReassignReadonlyVariable {
            get {
                return ResourceManager.GetString("CannotReassignReadonlyVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; does not evaluate to &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionDoesNotEvaluateToType {
            get {
                return ResourceManager.GetString("ExpressionDoesNotEvaluateToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression must have a value..
        /// </summary>
        internal static string ExpressionMustHaveValue {
            get {
                return ResourceManager.GetString("ExpressionMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is already declared..
        /// </summary>
        internal static string FieldAlreadyDeclared {
            get {
                return ResourceManager.GetString("FieldAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FieldDoesNotExist {
            get {
                return ResourceManager.GetString("FieldDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The float number &apos;{0}&apos; does not end with &apos;f&apos;.
        /// </summary>
        internal static string FloatNoMarker {
            get {
                return ResourceManager.GetString("FloatNoMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; already declared..
        /// </summary>
        internal static string FunctionAlreadyExists {
            get {
                return ResourceManager.GetString("FunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FunctionDoesNotExists {
            get {
                return ResourceManager.GetString("FunctionDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; expects a return type of &apos;{1}&apos; but no expression was found after &apos;return&apos; keyword..
        /// </summary>
        internal static string FunctionExpectsReturn {
            get {
                return ResourceManager.GetString("FunctionExpectsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a function..
        /// </summary>
        internal static string IdentifierIsNotAFunction {
            get {
                return ResourceManager.GetString("IdentifierIsNotAFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyword &apos;{0}&apos; can only be used inside loops..
        /// </summary>
        internal static string InvalidBreakOrContinue {
            get {
                return ResourceManager.GetString("InvalidBreakOrContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only assignment and call expressions can be used as a statement..
        /// </summary>
        internal static string InvalidExpressionStatement {
            get {
                return ResourceManager.GetString("InvalidExpressionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a variable..
        /// </summary>
        internal static string NameIsNotAVariable {
            get {
                return ResourceManager.GetString("NameIsNotAVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set namespace &apos;{0}&apos; because another namespace has already been set..
        /// </summary>
        internal static string NamespaceAlreadySet {
            get {
                return ResourceManager.GetString("NamespaceAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace definition &apos;{0}&apos; must be before any global statement..
        /// </summary>
        internal static string NamespaceMustBeFirstOfAny {
            get {
                return ResourceManager.GetString("NamespaceMustBeFirstOfAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native function &apos;{0}&apos; already declared..
        /// </summary>
        internal static string NativeFunctionAlreadyExists {
            get {
                return ResourceManager.GetString("NativeFunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all paths return in function &apos;{0}&apos;..
        /// </summary>
        internal static string NotAllPathsReturn {
            get {
                return ResourceManager.GetString("NotAllPathsReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is already declared..
        /// </summary>
        internal static string ParameterAlreadyDeclared {
            get {
                return ResourceManager.GetString("ParameterAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string TypeDoesNotExist {
            get {
                return ResourceManager.GetString("TypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operator &apos;{0}&apos; is not defined for type &apos;{1}&apos;..
        /// </summary>
        internal static string UnaryOperatorNotDefined {
            get {
                return ResourceManager.GetString("UnaryOperatorNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected global statement &apos;{0}&apos;..
        /// </summary>
        internal static string UnexpectedGlobalStatement {
            get {
                return ResourceManager.GetString("UnexpectedGlobalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token &apos;{0}&apos;, expected type &apos;{1}&apos;..
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated multi-line comment..
        /// </summary>
        internal static string UnterminatedMultilineComment {
            get {
                return ResourceManager.GetString("UnterminatedMultilineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal: &apos;{0}&apos;..
        /// </summary>
        internal static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not of type &apos;{1}&apos;..
        /// </summary>
        internal static string ValueNotOfType {
            get {
                return ResourceManager.GetString("ValueNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is already declared..
        /// </summary>
        internal static string VariableAlreadyDeclared {
            get {
                return ResourceManager.GetString("VariableAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name does not exist &apos;{0}&apos;..
        /// </summary>
        internal static string VariableDoesNotExists {
            get {
                return ResourceManager.GetString("VariableDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; does not have any fields..
        /// </summary>
        internal static string VariableDoesNotHaveAnyFields {
            get {
                return ResourceManager.GetString("VariableDoesNotHaveAnyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; does not have a return type. &apos;return&apos; keyword cannot be followed by an expression..
        /// </summary>
        internal static string VoidFunctionCannotReturnValue {
            get {
                return ResourceManager.GetString("VoidFunctionCannotReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; requires &apos;{1}&apos; arguments but was given {2}..
        /// </summary>
        internal static string WrongNumberOfArguments {
            get {
                return ResourceManager.GetString("WrongNumberOfArguments", resourceCulture);
            }
        }
    }
}
