//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Commons.Reporting.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Commons.Reporting.Strings.ParserMessages", typeof(ParserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; cannot be async invoked because it does not return void or object..
        /// </summary>
        public static string AsyncFunctionCallMustReturnVoidOrObject {
            get {
                return ResourceManager.GetString("AsyncFunctionCallMustReturnVoidOrObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; requires void return parameter..
        /// </summary>
        public static string AttributeRequiresVoidReturnType {
            get {
                return ResourceManager.GetString("AttributeRequiresVoidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; requires zero function parameters..
        /// </summary>
        public static string AttributeRequiresZeroParameters {
            get {
                return ResourceManager.GetString("AttributeRequiresZeroParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle {0}&apos; already declared..
        /// </summary>
        public static string BundleAlreadyExists {
            get {
                return ResourceManager.GetString("BundleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle &apos;{0}&apos; does not exist..
        /// </summary>
        public static string BundleDoesNotExist {
            get {
                return ResourceManager.GetString("BundleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is already declared..
        /// </summary>
        public static string FieldAlreadyDeclared {
            get {
                return ResourceManager.GetString("FieldAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; does not exist..
        /// </summary>
        public static string FieldDoesNotExist {
            get {
                return ResourceManager.GetString("FieldDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; already declared..
        /// </summary>
        public static string FunctionAlreadyExists {
            get {
                return ResourceManager.GetString("FunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace definition &apos;{0}&apos; must be before any global statement..
        /// </summary>
        public static string NamespaceAlreadySet {
            get {
                return ResourceManager.GetString("NamespaceAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace definition &apos;{0}&apos; must be before any global statement..
        /// </summary>
        public static string NamespaceMustBeFirstOfAny {
            get {
                return ResourceManager.GetString("NamespaceMustBeFirstOfAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native function &apos;{0}&apos; already declared..
        /// </summary>
        public static string NativeFunctionAlreadyExists {
            get {
                return ResourceManager.GetString("NativeFunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not exist..
        /// </summary>
        public static string TypeDoesNotExist {
            get {
                return ResourceManager.GetString("TypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected global statement &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedGlobalStatement {
            get {
                return ResourceManager.GetString("UnexpectedGlobalStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal: &apos;{0}&apos;..
        /// </summary>
        public static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is already declared..
        /// </summary>
        public static string VariableAlreadyDeclared {
            get {
                return ResourceManager.GetString("VariableAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; is not of type &apos;{1}&apos;..
        /// </summary>
        public static string VariableNotOfType {
            get {
                return ResourceManager.GetString("VariableNotOfType", resourceCulture);
            }
        }
    }
}
