//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.SourceGeneration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.SourceGeneration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml-model href=&quot;Opcodes.xsd&quot;?&gt;
        ///&lt;Opcodes&gt;
        ///    &lt;Opcode Type=&quot;Nop&quot;&gt;
        ///        &lt;Description&gt;Empty operation&lt;/Description&gt;
        ///    &lt;/Opcode&gt;
        ///    &lt;Opcode Type=&quot;Pop&quot;&gt;
        ///        &lt;Description&gt;Pop the value on top of the stack&lt;/Description&gt;
        ///    &lt;/Opcode&gt;
        ///    &lt;Opcode Type=&quot;Dup&quot;&gt;
        ///        &lt;Description&gt;Duplicates value on top of stack&lt;/Description&gt;
        ///    &lt;/Opcode&gt;
        ///    &lt;Opcode Type=&quot;Call&quot;&gt;
        ///        &lt;Description&gt;Invoke function&lt;/Description&gt;
        ///    &lt;/Opcode&gt;
        ///    &lt;Opcode Type=&quot;ConvType&quot;&gt;
        ///        &lt;Description&gt;Convert the top of the stac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Opcodes {
            get {
                return ResourceManager.GetString("Opcodes", resourceCulture);
            }
        }
    }
}
