using Nebula.Core.Compilation.AST.Symbols;
using Nebula.Interop.Enumerators;
using OmniSharp.Extensions.LanguageServer.Protocol.Models;
using System.Collections.Generic;
using System.Linq;

namespace Nebula.LSP.CompletionAnalyzers
{
    /// <summary> Generates completion items for the currently available functions that can be invoked without specifing a namespace</summary>
    public class AvailableLocalFunctionsProvider
        : ICompletionProvider
    {
        public bool IsApplicable(NebulaCompletionContext context)
        {
            return context.IsInFunction;
        }

        public IEnumerable<CompletionItem> Provide(NebulaCompletionContext context)
        {
            var scriptFunctions = context.Program.Functions.Keys.Concat(context.Program.NativeFunctions)
                .Where(f => f.Attributes.FirstOrDefault(a => a.Is(AttributeType.AutoGenerated)) == null);

            foreach (FunctionSymbol function in scriptFunctions)
            {
                yield return new CompletionItem
                {
                    Kind = CompletionItemKind.Function,
                    InsertText = function.Name,
                    InsertTextFormat = InsertTextFormat.PlainText,
                    InsertTextMode = InsertTextMode.AsIs,
                    Label = function.Name,
                };
            }
        }
    }
}