namespace Nebula.Interop.Enumerators
{
    public enum AttributeType
    {
        Unknown,
        /// <summary> The function will run as soon as the script is loaded into the virtual machine</summary>
        AutoExec,
        /// <summary> Not implement </summary>
        ExecAfter,
        /// <summary> The function was generated by the compiler </summary>
        AutoGenerated,
        /// <summary> The execution of this function cannot be interrupted by the thread scheduler </summary>
        Initializer,
        LastAttribute,
    }
}
